# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'mod2' do
  pod 'AppCenterReactNativeShared', '~> 1.13.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mod2

  platform :ios, '9.0'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'mod2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mod2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mod2-tvOS

  target 'mod2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
